name: Label Pull Requests
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v5.0.0
      with:
        repo-token: "${{ secrets.WALL_BREW_BOT_PAT }}"
